const barnehager = {
    "type": "FeatureCollection",
    "name": "Barnehage",
    "features": [
      {
        "type": "Feature",
        "properties": {
          "gml_id": "id8489eeec-7dcb-492e-a646-f10828a802f8",
          "lokalId": "46847f23-9aae-4d88-b756-3396c5dc9659",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Rønholt barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 972286419,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 37,
          "antallAnsatte": 16,
          "antallBarnPerBarnehagelærer": 11.3,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "06:45",
          "åpningstidTil": "16:45",
          "adressenavn": "Rønholtveien 71",
          "postnummer": 3967,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.5714376, 58.9738984] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "ided1abc93-432f-4abb-b514-16126e6ce790",
          "lokalId": "57469ab7-2961-4539-a148-2a9728f6e9be",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Tirilltoppen barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 973494597,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 52,
          "antallAnsatte": 27,
          "antallBarnPerBarnehagelærer": 14.0,
          "eierforhold": "Privat",
          "kostpenger": 450,
          "åpningstidFra": "07:15",
          "åpningstidTil": "16:30",
          "adressenavn": "Reiduns vei 5",
          "postnummer": 3961,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/",
          "lenkeHjemmeside": "http://www.tirilltoppen.barnehage.no"
        },
        "geometry": { "type": "Point", "coordinates": [9.7075737, 59.0239685] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "idc0d7a65c-addb-4f42-a00f-e187325dd499",
          "lokalId": "7f3afacf-6a50-4079-b6d2-ed91a54c69b1",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Sundby barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 975295516,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 50,
          "antallAnsatte": 18,
          "antallBarnPerBarnehagelærer": 13.0,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:45",
          "adressenavn": "Sykehjemsveien 2",
          "postnummer": 3961,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.7253786, 59.0193257] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "id64a2f856-69a6-4b83-8f0f-b97cc4295990",
          "lokalId": "4ff2ca95-d7b4-4d94-aae4-c65317de0d06",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Falkåsen Kunst- og kulturbarnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 975297101,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 35,
          "antallAnsatte": 16,
          "antallBarnPerBarnehagelærer": 12.0,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:45",
          "adressenavn": "Falkåsveien 14",
          "postnummer": 3960,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.6941423, 59.0420389] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "id9e8c4b63-8ec3-4c37-9312-c1899bced1d5",
          "lokalId": "a7385c84-672f-4b6f-8b1a-d3d34df4abe4",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Nustad barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 975307158,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 100,
          "antallAnsatte": 29,
          "antallBarnPerBarnehagelærer": 12.5,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:30",
          "adressenavn": "Øvre Nustadvei 30",
          "postnummer": 3970,
          "poststed": "Langesund",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.7288418, 59.0108013] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "id3942a1da-4385-4507-9e9a-71f97f15dd56",
          "lokalId": "8b5846ab-5c7c-4256-889a-d9685ee9252a",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:52",
          "målemetode": 99,
          "barnehagenavn": "Uksodden barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 975307166,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 36,
          "antallAnsatte": 14,
          "antallBarnPerBarnehagelærer": 11.8,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:30",
          "adressenavn": "Strandveien 6B",
          "postnummer": 3965,
          "poststed": "Herre",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.5477942, 59.1147923] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "idcdaf07cd-075a-49f8-9c92-e4d93d0efbe7",
          "lokalId": "61765b23-68ad-43ed-821d-e1c29e048418",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:53",
          "målemetode": 99,
          "barnehagenavn": "Solstua kulturbarnehage AS",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 984684134,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 37,
          "antallAnsatte": 14,
          "antallBarnPerBarnehagelærer": 12.3,
          "eierforhold": "Privat",
          "kostpenger": 300,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:30",
          "adressenavn": "Reiduns vei 1",
          "postnummer": 3961,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.7077721, 59.0242998] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "ida6b5f5e9-abed-4b68-affa-591c62412c8d",
          "lokalId": "4f1b1f5a-80a1-491e-a142-c63744dc12be",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:53",
          "målemetode": 99,
          "barnehagenavn": "Stokkevannet barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 985488886,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 47,
          "antallAnsatte": 17,
          "antallBarnPerBarnehagelærer": 13.2,
          "eierforhold": "Offentlig",
          "kostpenger": 400,
          "åpningstidFra": "06:45",
          "åpningstidTil": "16:45",
          "adressenavn": "Europaveien 135",
          "postnummer": 3962,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.672562, 59.0373209] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "id300111d6-d849-43d1-b758-606a06d1f945",
          "lokalId": "5b99c723-73f6-44ae-bab9-a22fe18f6777",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:53",
          "målemetode": 99,
          "barnehagenavn": "Grasmyr naturbarnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 987130008,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 77,
          "antallAnsatte": 25,
          "antallBarnPerBarnehagelærer": 11.9,
          "eierforhold": "Offentlig",
          "kostpenger": 328,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:45",
          "adressenavn": "Tønderveien 11",
          "postnummer": 3961,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/",
          "lenkeHjemmeside": "http://www.bamble.kommune.no/SB/barnehager/grasmyr-barnehage/"
        },
        "geometry": { "type": "Point", "coordinates": [9.7024233, 59.0293671] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "idba19ff9f-b502-4427-a94e-c597389f4749",
          "lokalId": "0e32bc89-fc0e-404e-9261-2223954c23fc",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:53",
          "målemetode": 99,
          "barnehagenavn": "Læringsverkstedet Marthas Hage idrettsbarnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 996566528,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 81,
          "antallAnsatte": 28,
          "antallBarnPerBarnehagelærer": 14.5,
          "eierforhold": "Privat",
          "kostpenger": 475,
          "åpningstidFra": "06:30",
          "åpningstidTil": "17:00",
          "adressenavn": "Hans Petters vei 19",
          "postnummer": 3962,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.6560638, 59.0453358] }
      },
      {
        "type": "Feature",
        "properties": {
          "gml_id": "ida573f38f-bb39-4532-a441-576c9f1a1976",
          "lokalId": "bd490542-0c37-49e8-a362-aa0b35be873e",
          "navnerom": "https://data.geonorge.no/sosi/befolkning",
          "versjonId": 20210801,
          "datauttaksdato": "2024-11-06T11:57:53",
          "målemetode": 99,
          "barnehagenavn": "Grashoppa barnehage",
          "iDrift": true,
          "barnehagetype": "OrdinærBarnehage",
          "organisasjonsnummer": 998010942,
          "høyesteAlder": 5,
          "lavesteAlder": 1,
          "antallBarn": 52,
          "antallAnsatte": 19,
          "antallBarnPerBarnehagelærer": 13.6,
          "eierforhold": "Privat",
          "kostpenger": 450,
          "åpningstidFra": "07:00",
          "åpningstidTil": "16:45",
          "adressenavn": "Sundbykåsa 26",
          "postnummer": 3961,
          "poststed": "Stathelle",
          "kommunenavn": "Bamble",
          "kommunenummer": 4012,
          "fylkesnummer": 40,
          "fylkesnavn": "Telemark",
          "lenkeSøknadsskjema": "http://www.bamble.kommune.no/"
        },
        "geometry": { "type": "Point", "coordinates": [9.7050187, 59.0258152] }
      }
    ]
  }

  export default barnehager;
  